package com.example.domain

enum class AppLanguage(
    val code: String,
    val nativeName: String,
    val englishName: String,
    val flagEmoji: String,
    val currencySymbol: String
) {
    ENGLISH("EN", "English", "English", "🇺🇸", "$"),
    BENGALI("BN", "বাংলা", "Bengali", "🇧🇩", "৳"),
    INDONESIAN("ID", "Bahasa Indonesia", "Indonesian", "🇮🇩", "Rp"),
    HINDI("HI", "हिन्दी", "Hindi", "🇮🇳", "₹"),
    URDU("UR", "اردو", "Urdu", "🇵🇰", "Rs"),
    ARABIC("AR", "العربية", "Arabic", "🇸🇦", "﷼"),
    SPANISH("ES", "Español", "Spanish", "🇪🇸", "$"),
    PORTUGUESE("PT", "Português", "Portuguese", "🇧🇷", "R$");

    companion object {
        fun fromCode(code: String): AppLanguage =
            entries.find { it.code.equals(code, ignoreCase = true) } ?: ENGLISH
    }
}

data class LocalizedStrings(
    val withdrawBtn: String,
    val moreToWithdrawTop: (String, String) -> String,
    val levelLabel: (Int) -> String,
    val noWithdrawUpdate: String,
    val tutorialBanner: String,
    val pinchToZoomHint: String,
    val taskCenterTitle: String,
    val dailyTasksTab: String,
    val careerTasksTab: String,
    val claimBtn: String,
    val incompleteBtn: String,
    val claimedBtn: String,
    val dailyLoginTask: String,
    val completeLevelsTask: (Int) -> String,
    val watchAdsTask: (Int) -> String,
    val taskRewardTitle: String,
    val levelSuccessTitle: String,
    val watchAdToClaimBtn: String,
    val claimBaseOnlyBtn: (String) -> String,
    val nextLevelBtn: String,
    val watchingVideoToast: String,
    val continueHeader: String,
    val outOfLivesTitle: String,
    val outOfLivesSubtitle: String,
    val freeReviveBtn: String,
    val tryAgainBtn: String,
    val withdrawScreenTitle: String,
    val currentBalanceLabel: String,
    val withdrawTierSection: String,
    val withdrawInstructionsSection: String,
    val withdrawRuleText: (String) -> String,
    val withdrawNeededText: (String, String) -> String,
    val withdrawActionBtn: (String) -> String,
    val accountDetailsHeader: String,
    val selectAccountMethodSubtitle: String,
    val accountInputPlaceholder: String,
    val nameInputPlaceholder: String,
    val submitBtn: String,
    val confirmWithdrawHeader: String,
    val accountFieldLabel: String,
    val nameFieldLabel: String,
    val invalidAccountToast: String,
    val insufficientBalanceToast: (String) -> String,
    val withdrawSubmittedToast: (String) -> String,
    val settingsTitle: String,
    val soundLabel: String,
    val vibrationLabel: String,
    val languageLabel: String,
    val selectLevelLabel: String,
    val restartLevelLabel: String,
    val closeBtn: String,
    val broadcastMessages: List<String>
)

fun getStrings(lang: AppLanguage): LocalizedStrings {
    val sym = lang.currencySymbol
    return when (lang) {
        AppLanguage.BENGALI -> LocalizedStrings(
            withdrawBtn = "উত্তোলন",
            moreToWithdrawTop = { need, min -> "আরও $sym $need\n$sym $min উত্তোলন করতে" },
            levelLabel = { lvl -> "লেভেল $lvl" },
            noWithdrawUpdate = "কোনো উত্তোলন আপডেট নেই",
            tutorialBanner = "লেভেল সম্পন্ন করে নগদ পুরস্কার অর্জন করুন। যত বেশি লেভেল সম্পন্ন করবেন, তত বেশি উপার্জন করার সুযোগ!",
            pinchToZoomHint = "জুম করতে আঙুল বাইরে টানুন",
            taskCenterTitle = "টাস্ক সেন্টার",
            dailyTasksTab = "দৈনিক টাস্ক",
            careerTasksTab = "ক্যারিয়ার টাস্ক",
            claimBtn = "দাবি করুন",
            incompleteBtn = "অসম্পূর্ণ",
            claimedBtn = "সম্পন্ন",
            dailyLoginTask = "দৈনিক লগইন",
            completeLevelsTask = { n -> "${n}টি লেভেল সম্পন্ন করুন" },
            watchAdsTask = { n -> "${n}টি বিজ্ঞাপন দেখুন" },
            taskRewardTitle = "টাস্ক পুরস্কার",
            levelSuccessTitle = "সফল",
            watchAdToClaimBtn = "দাবি করতে বিজ্ঞাপন দেখুন",
            claimBaseOnlyBtn = { amt -> "শুধু $sym $amt দাবি করুন" },
            nextLevelBtn = "পরবর্তী লেভেল (Next Level)",
            watchingVideoToast = "ভিডিও দেখে বড় পুরস্কার দাবি করুন",
            continueHeader = "চালিয়ে যাবেন?",
            outOfLivesTitle = "লাইফ শেষ!",
            outOfLivesSubtitle = "হাল ছাড়বেন না! বিনামূল্যে পুনরুজ্জীবিত হয়ে লড়াই চালিয়ে যান!",
            freeReviveBtn = "বিনামূল্যে পুনরুজ্জীবন",
            tryAgainBtn = "আবার চেষ্টা করুন",
            withdrawScreenTitle = "উত্তোলন",
            currentBalanceLabel = "বর্তমান ব্যালেন্স",
            withdrawTierSection = "উত্তোলন স্তর",
            withdrawInstructionsSection = "উত্তোলন নির্দেশাবলী:",
            withdrawRuleText = { tier -> "প্ল্যাটফর্মের নিয়ম অনুযায়ী, এই স্তরের পেমেন্ট পরিমাণ $sym $tier" },
            withdrawNeededText = { tier, need -> "$sym $tier উত্তোলন করতে, আপনার আরও $sym $need প্রয়োজন" },
            withdrawActionBtn = { tier -> "$sym $tier উত্তোলন করুন" },
            accountDetailsHeader = "অ্যাকাউন্টের বিবরণ দিন",
            selectAccountMethodSubtitle = "অ্যাকাউন্ট তথ্য নির্বাচন করুন",
            accountInputPlaceholder = "কৃপা করে আপনার অ্যাকাউন্টটি (মোবাইল নাম্বার বা ইমেইল) লিখুন",
            nameInputPlaceholder = "কৃপা করে আপনার নাম লিখুন",
            submitBtn = "জমা দিন",
            confirmWithdrawHeader = "উত্তোলনের তথ্য নিশ্চিত করুন",
            accountFieldLabel = "হিসাব",
            nameFieldLabel = "নাম",
            invalidAccountToast = "সঠিক অ্যাকাউন্ট ইনপুট করুন",
            insufficientBalanceToast = { need -> "অপর্যাপ্ত ব্যালেন্স, $sym $need কম আছে" },
            withdrawSubmittedToast = { tier -> "$sym $tier উত্তোলনের অনুরোধ জমা হয়েছে!" },
            settingsTitle = "সেটিংস ও ভাষা",
            soundLabel = "সাউন্ড ইফেক্ট",
            vibrationLabel = "ভাইব্রেশন",
            languageLabel = "ভাষা নির্বাচন করুন (Language)",
            selectLevelLabel = "লেভেল নির্বাচন করুন (100+ Levels)",
            restartLevelLabel = "এই লেভেল পুনরায় শুরু করুন",
            closeBtn = "বন্ধ করুন",
            broadcastMessages = listOf(
                "অভিনন্দন আরাফ***! সফলভাবে $sym 10,000 উত্তোলন করেছেন!",
                "অভিনন্দন ফাতেমা***! সফলভাবে $sym 5,000 উত্তোলন করেছেন!",
                "অভিনন্দন কামা***! সফলভাবে $sym 20,000 উত্তোলন করেছেন!",
                "অভিনন্দন তানভ***! সফলভাবে $sym 30,000 উত্তোলন করেছেন!"
            )
        )

        AppLanguage.INDONESIAN -> LocalizedStrings(
            withdrawBtn = "withdraw",
            moreToWithdrawTop = { need, min -> "Kurang $sym $need lagi\nuntuk menarik $sym $min" },
            levelLabel = { lvl -> "Level $lvl" },
            noWithdrawUpdate = "Belum ada pembaruan penarikan",
            tutorialBanner = "Selesaikan level untuk mendapatkan hadiah uang tunai! Semakin banyak level selesai, semakin besar penghasilanmu!",
            pinchToZoomHint = "Rentangkan jari untuk memperbesar",
            taskCenterTitle = "Pusat Tugas",
            dailyTasksTab = "Tugas Harian",
            careerTasksTab = "Tugas Karier",
            claimBtn = "Klaim",
            incompleteBtn = "Belum Selesai",
            claimedBtn = "Diklaim",
            dailyLoginTask = "Login harian",
            completeLevelsTask = { n -> "Lewati $n level" },
            watchAdsTask = { n -> "Tonton $n iklan" },
            taskRewardTitle = "Hadiah Tugas",
            levelSuccessTitle = "Berhasil!",
            watchAdToClaimBtn = "Tonton iklan untuk klaim",
            claimBaseOnlyBtn = { amt -> "Klaim $sym $amt saja" },
            nextLevelBtn = "Level Berikutnya (Next Level)",
            watchingVideoToast = "Tonton video untuk hadiah besar",
            continueHeader = "Lanjutkan?",
            outOfLivesTitle = "Nyawa Habis!",
            outOfLivesSubtitle = "Jangan menyerah! Bangkit gratis dan lanjutkan bermain!",
            freeReviveBtn = "Bangkit Gratis",
            tryAgainBtn = "Coba Lagi",
            withdrawScreenTitle = "Penarikan",
            currentBalanceLabel = "Saldo Saat Ini",
            withdrawTierSection = "Tingkat Penarikan",
            withdrawInstructionsSection = "Instruksi Penarikan:",
            withdrawRuleText = { tier -> "Sesuai aturan platform, jumlah pembayaran tingkat ini adalah $sym $tier" },
            withdrawNeededText = { tier, need -> "Untuk menarik $sym $tier, Anda butuh $sym $need lagi" },
            withdrawActionBtn = { tier -> "Tarik $sym $tier" },
            accountDetailsHeader = "Detail Akun",
            selectAccountMethodSubtitle = "Pilih metode pembayaran",
            accountInputPlaceholder = "Masukkan nomor ponsel atau email akun Anda",
            nameInputPlaceholder = "Masukkan nama lengkap Anda",
            submitBtn = "Kirim",
            confirmWithdrawHeader = "Konfirmasi Penarikan",
            accountFieldLabel = "Akun",
            nameFieldLabel = "Nama",
            invalidAccountToast = "Masukkan nomor akun yang valid",
            insufficientBalanceToast = { need -> "Saldo tidak cukup, kurang $sym $need" },
            withdrawSubmittedToast = { tier -> "Permintaan penarikan $sym $tier berhasil dikirim!" },
            settingsTitle = "Pengaturan & Bahasa",
            soundLabel = "Efek Suara",
            vibrationLabel = "Getaran",
            languageLabel = "Pilih Bahasa (Language)",
            selectLevelLabel = "Pilih Level (100+ Level)",
            restartLevelLabel = "Ulangi Level Ini",
            closeBtn = "Tutup",
            broadcastMessages = listOf(
                "Selamat p***a berhasil menarik $sym 2.000.000!",
                "Selamat s***h berhasil menarik $sym 5.000.000!",
                "Selamat Lili***i berhasil menarik $sym 1.000.000!",
                "Selamat Budi***o berhasil menarik $sym 8.000.000!"
            )
        )

        AppLanguage.HINDI -> LocalizedStrings(
            withdrawBtn = "निकासी",
            moreToWithdrawTop = { need, min -> "$sym $min निकालने के लिए\n$sym $need और चाहिए" },
            levelLabel = { lvl -> "लेवल $lvl" },
            noWithdrawUpdate = "कोई निकासी अपडेट नहीं",
            tutorialBanner = "लेवल पूरा करके नकद पुरस्कार जीतें! जितने अधिक लेवल पूरे करेंगे, उतनी अधिक कमाई होगी!",
            pinchToZoomHint = "ज़ूम करने के लिए उंगलियां फैलाएं",
            taskCenterTitle = "टास्क सेंटर",
            dailyTasksTab = "दैनिक टास्क",
            careerTasksTab = "करियर टास्क",
            claimBtn = "प्राप्त करें",
            incompleteBtn = "अधूरा",
            claimedBtn = "प्राप्त किया",
            dailyLoginTask = "दैनिक लॉगिन",
            completeLevelsTask = { n -> "$n लेवल पूरे करें" },
            watchAdsTask = { n -> "$n विज्ञापन देखें" },
            taskRewardTitle = "टास्क इनाम",
            levelSuccessTitle = "सफल!",
            watchAdToClaimBtn = "इनाम पाने के लिए वीडियो देखें",
            claimBaseOnlyBtn = { amt -> "केवल $sym $amt प्राप्त करें" },
            nextLevelBtn = "अगला लेवल (Next Level)",
            watchingVideoToast = "बड़ा इनाम पाने के लिए वीडियो देख रहे हैं...",
            continueHeader = "जारी रखें?",
            outOfLivesTitle = "लाइफ समाप्त!",
            outOfLivesSubtitle = "हार मत मानो! मुफ्त में रिवाइव करें और खेल जारी रखें!",
            freeReviveBtn = "मुफ्त रिवाइव",
            tryAgainBtn = "पुनः प्रयास करें",
            withdrawScreenTitle = "निकासी (Withdraw)",
            currentBalanceLabel = "वर्तमान बैलेंस",
            withdrawTierSection = "निकासी स्तर",
            withdrawInstructionsSection = "निकासी निर्देश:",
            withdrawRuleText = { tier -> "प्लेटफ़ॉर्म नियमों के अनुसार, इस स्तर की भुगतान राशि $sym $tier है" },
            withdrawNeededText = { tier, need -> "$sym $tier निकालने के लिए आपको $sym $need और चाहिए" },
            withdrawActionBtn = { tier -> "$sym $tier निकालें" },
            accountDetailsHeader = "खाता विवरण दर्ज करें",
            selectAccountMethodSubtitle = "भुगतान विधि चुनें",
            accountInputPlaceholder = "कृपया अपना मोबाइल नंबर या ईमेल दर्ज करें",
            nameInputPlaceholder = "कृपया अपना नाम दर्ज करें",
            submitBtn = "जमा करें",
            confirmWithdrawHeader = "निकासी जानकारी की पुष्टि करें",
            accountFieldLabel = "खाता",
            nameFieldLabel = "नाम",
            invalidAccountToast = "कृपया सही खाता नंबर दर्ज करें",
            insufficientBalanceToast = { need -> "अपर्याप्त बैलेंस, $sym $need कम है" },
            withdrawSubmittedToast = { tier -> "$sym $tier निकासी अनुरोध सफलतापूर्वक भेजा गया!" },
            settingsTitle = "सेटिंग्स और भाषा",
            soundLabel = "साउंड इफेक्ट",
            vibrationLabel = "वाइब्रेशन",
            languageLabel = "भाषा चुनें (Language)",
            selectLevelLabel = "लेवल चुनें (100+ Levels)",
            restartLevelLabel = "लेवल फिर से शुरू करें",
            closeBtn = "बंद करें",
            broadcastMessages = listOf(
                "बधाई हो आर***! सफलतापूर्वक $sym 7,100 निकाले!",
                "बधाई हो प्रिया***! सफलतापूर्वक $sym 3,550 निकाले!",
                "बधाई हो राहुल***! सफलतापूर्वक $sym 14,200 निकाले!",
                "बधाई हो अमन***! सफलतापूर्वक $sym 21,300 निकाले!"
            )
        )

        AppLanguage.URDU -> LocalizedStrings(
            withdrawBtn = "نکالیں",
            moreToWithdrawTop = { need, min -> "مزید $sym $need درکار ہیں\n$sym $min نکالنے کے لیے" },
            levelLabel = { lvl -> "لیول $lvl" },
            noWithdrawUpdate = "کوئی نئی اپڈیٹ نہیں",
            tutorialBanner = "لیول مکمل کر کے نقد انعامات حاصل کریں! جتنے زیادہ لیول مکمل کریں گے، اتنا زیادہ انعام!",
            pinchToZoomHint = "زوم کرنے کے لیے انگلیاں پھیلائیں",
            taskCenterTitle = "ٹاسک سینٹر",
            dailyTasksTab = "روزانہ ٹاسک",
            careerTasksTab = "کیریئر ٹاسک",
            claimBtn = "حاصل کریں",
            incompleteBtn = "نامکمل",
            claimedBtn = "مکمل",
            dailyLoginTask = "روزانہ لاگ ان",
            completeLevelsTask = { n -> "$n لیول مکمل کریں" },
            watchAdsTask = { n -> "$n اشتہارات دیکھیں" },
            taskRewardTitle = "ٹاسک انعام",
            levelSuccessTitle = "کامیاب!",
            watchAdToClaimBtn = "انعام کے لیے ویڈیو دیکھیں",
            claimBaseOnlyBtn = { amt -> "صرف $sym $amt حاصل کریں" },
            nextLevelBtn = "اگلا لیول (Next Level)",
            watchingVideoToast = "بڑا انعام حاصل کیا جا رہا ہے...",
            continueHeader = "جاری رکھیں؟",
            outOfLivesTitle = "لائف ختم!",
            outOfLivesSubtitle = "ہمت نہ ہاریں! مفت میں ریوائیو کریں اور کھیل جاری رکھیں!",
            freeReviveBtn = "مفت ریوائیو",
            tryAgainBtn = "دوبارہ کوشش کریں",
            withdrawScreenTitle = "رقم نکالیں",
            currentBalanceLabel = "موجودہ بیلنس",
            withdrawTierSection = "رقم کی حد",
            withdrawInstructionsSection = "ہدایات:",
            withdrawRuleText = { tier -> "پلیٹ فارم کے اصولوں کے مطابق اس درجے کی رقم $sym $tier ہے" },
            withdrawNeededText = { tier, need -> "$sym $tier نکالنے کے لیے مزید $sym $need درکار ہیں" },
            withdrawActionBtn = { tier -> "$sym $tier نکالیں" },
            accountDetailsHeader = "اکاؤنٹ کی تفصیلات",
            selectAccountMethodSubtitle = "ادائیگی کا طریقہ منتخب کریں",
            accountInputPlaceholder = "اپنا موبائل نمبر یا ای میل درج کریں",
            nameInputPlaceholder = "اپنا نام درج کریں",
            submitBtn = "جمع کریں",
            confirmWithdrawHeader = "تفصیلات کی تصدیق کریں",
            accountFieldLabel = "اکاؤنٹ",
            nameFieldLabel = "نام",
            invalidAccountToast = "براہ کرم درست اکاؤنٹ نمبر درج کریں",
            insufficientBalanceToast = { need -> "ناکافی بیلنس، مزید $sym $need درکار ہیں" },
            withdrawSubmittedToast = { tier -> "$sym $tier نکالنے کی درخواست جمع ہو گئی!" },
            settingsTitle = "سیٹنگز اور زبان",
            soundLabel = "آواز (Sound)",
            vibrationLabel = "وائبریشن",
            languageLabel = "زبان منتخب کریں (Language)",
            selectLevelLabel = "لیول منتخب کریں (100+ Levels)",
            restartLevelLabel = "لیول دوبارہ شروع کریں",
            closeBtn = "بند کریں",
            broadcastMessages = listOf(
                "مبارک ہو علی***! کامیابی سے $sym 18,640 نکال لیے!",
                "مبارک ہو فاطمہ***! کامیابی سے $sym 11,650 نکال لیے!",
                "مبارک ہو کامران***! کامیابی سے $sym 23,300 نکال لیے!"
            )
        )

        AppLanguage.ARABIC -> LocalizedStrings(
            withdrawBtn = "سحب",
            moreToWithdrawTop = { need, min -> "تحتاج $sym $need إضافية\nلسحب $sym $min" },
            levelLabel = { lvl -> "مستوى $lvl" },
            noWithdrawUpdate = "لا توجد تحديثات سحب",
            tutorialBanner = "أكمل المستويات لكسب مكافآت نقدية! كلما أكملت مستويات أكثر، زادت فرص ربحك!",
            pinchToZoomHint = "اسحب بإصبعيك للتكبير",
            taskCenterTitle = "مركز المهام",
            dailyTasksTab = "المهام اليومية",
            careerTasksTab = "مهام المسيرة",
            claimBtn = "مطالبة",
            incompleteBtn = "غير مكتمل",
            claimedBtn = "تمت المطالبة",
            dailyLoginTask = "تسجيل الدخول اليومي",
            completeLevelsTask = { n -> "أكمل $n مستويات" },
            watchAdsTask = { n -> "شاهد $n إعلانات" },
            taskRewardTitle = "مكافأة المهمة",
            levelSuccessTitle = "نجاح!",
            watchAdToClaimBtn = "شاهد الفيديو للمطالبة بالمكافأة",
            claimBaseOnlyBtn = { amt -> "المطالبة بـ $sym $amt فقط" },
            nextLevelBtn = "المستوى التالي (Next Level)",
            watchingVideoToast = "شاهد الفيديو للحصول على المكافأة الكبرى",
            continueHeader = "هل تريد المتابعة؟",
            outOfLivesTitle = "انتهت القلوب!",
            outOfLivesSubtitle = "لا تستسلم! استعد قلوبك مجاناً وواصل اللعب!",
            freeReviveBtn = "إحياء مجاني",
            tryAgainBtn = "حاول مرة أخرى",
            withdrawScreenTitle = "السحب",
            currentBalanceLabel = "الرصيد الحالي",
            withdrawTierSection = "فئات السحب",
            withdrawInstructionsSection = "تعليمات السحب:",
            withdrawRuleText = { tier -> "وفقاً لقواعد المنصة، قيمة الدفع لهذه الفئة هي $sym $tier" },
            withdrawNeededText = { tier, need -> "لسحب $sym $tier، تحتاج إلى $sym $need إضافية" },
            withdrawActionBtn = { tier -> "سحب $sym $tier" },
            accountDetailsHeader = "تفاصيل الحساب",
            selectAccountMethodSubtitle = "اختر طريقة الدفع",
            accountInputPlaceholder = "يرجى إدخال رقم الهاتف أو البريد الإلكتروني",
            nameInputPlaceholder = "يرجى إدخال الاسم الكامل",
            submitBtn = "إرسال",
            confirmWithdrawHeader = "تأكيد معلومات السحب",
            accountFieldLabel = "الحساب",
            nameFieldLabel = "الاسم",
            invalidAccountToast = "يرجى إدخال حساب صحيح",
            insufficientBalanceToast = { need -> "الرصيد غير كافٍ، ينقصك $sym $need" },
            withdrawSubmittedToast = { tier -> "تم إرسال طلب سحب $sym $tier بنجاح!" },
            settingsTitle = "الإعدادات واللغة",
            soundLabel = "المؤثرات الصوتية",
            vibrationLabel = "الاهتزاز",
            languageLabel = "اختر اللغة (Language)",
            selectLevelLabel = "اختر المستوى (100+ Levels)",
            restartLevelLabel = "إعادة تشغيل المستوى",
            closeBtn = "إغلاق",
            broadcastMessages = listOf(
                "تهانينا أحمد***! قام بسحب $sym 248.00 بنجاح!",
                "تهانينا فاطمة***! قامت بسحب $sym 155.00 بنجاح!",
                "تهانينا خالد***! قام بسحب $sym 310.00 بنجاح!"
            )
        )

        AppLanguage.SPANISH -> LocalizedStrings(
            withdrawBtn = "Retirar",
            moreToWithdrawTop = { need, min -> "Faltan $sym $need\npara retirar $sym $min" },
            levelLabel = { lvl -> "Nivel $lvl" },
            noWithdrawUpdate = "Sin actualizaciones de retiro",
            tutorialBanner = "¡Completa niveles para ganar recompensas! ¡Cuantos más niveles completes, más ganarás!",
            pinchToZoomHint = "Separa los dedos para hacer zoom",
            taskCenterTitle = "Centro de Tareas",
            dailyTasksTab = "Tareas Diarias",
            careerTasksTab = "Tareas de Carrera",
            claimBtn = "Reclamar",
            incompleteBtn = "Incompleto",
            claimedBtn = "Reclamado",
            dailyLoginTask = "Inicio de sesión diario",
            completeLevelsTask = { n -> "Completa $n niveles" },
            watchAdsTask = { n -> "Ver $n videos" },
            taskRewardTitle = "Premio de Tarea",
            levelSuccessTitle = "¡Éxito!",
            watchAdToClaimBtn = "Ver video para reclamar todo",
            claimBaseOnlyBtn = { amt -> "Reclamar solo $sym $amt" },
            nextLevelBtn = "Siguiente Nivel (Next Level)",
            watchingVideoToast = "Reclamando gran recompensa...",
            continueHeader = "¿Continuar?",
            outOfLivesTitle = "¡Sin Vidas!",
            outOfLivesSubtitle = "¡No te rindas! ¡Revive gratis y sigue jugando!",
            freeReviveBtn = "Revivir Gratis",
            tryAgainBtn = "Intentar de nuevo",
            withdrawScreenTitle = "Retirar",
            currentBalanceLabel = "Saldo Actual",
            withdrawTierSection = "Niveles de Retiro",
            withdrawInstructionsSection = "Instrucciones de Retiro:",
            withdrawRuleText = { tier -> "Según las reglas, el monto de pago de este nivel es $sym $tier" },
            withdrawNeededText = { tier, need -> "Para retirar $sym $tier, necesitas $sym $need más" },
            withdrawActionBtn = { tier -> "Retirar $sym $tier" },
            accountDetailsHeader = "Detalles de la Cuenta",
            selectAccountMethodSubtitle = "Selecciona método de pago",
            accountInputPlaceholder = "Ingresa tu número de móvil o correo",
            nameInputPlaceholder = "Ingresa tu nombre completo",
            submitBtn = "Enviar",
            confirmWithdrawHeader = "Confirmar Retiro",
            accountFieldLabel = "Cuenta",
            nameFieldLabel = "Nombre",
            invalidAccountToast = "Ingresa una cuenta válida",
            insufficientBalanceToast = { need -> "Saldo insuficiente, faltan $sym $need" },
            withdrawSubmittedToast = { tier -> "¡Solicitud de retiro de $sym $tier enviada!" },
            settingsTitle = "Ajustes e Idioma",
            soundLabel = "Efectos de Sonido",
            vibrationLabel = "Vibración",
            languageLabel = "Seleccionar Idioma (Language)",
            selectLevelLabel = "Seleccionar Nivel (100+ Niveles)",
            restartLevelLabel = "Reiniciar Nivel",
            closeBtn = "Cerrar",
            broadcastMessages = listOf(
                "¡Felicidades Carlos***! ¡Retiró $sym 67.20 con éxito!",
                "¡Felicidades Sofía***! ¡Retiró $sym 42.00 con éxito!",
                "¡Felicidades Mateo***! ¡Retiró $sym 84.00 con éxito!"
            )
        )

        AppLanguage.PORTUGUESE -> LocalizedStrings(
            withdrawBtn = "Sacar",
            moreToWithdrawTop = { need, min -> "Faltam $sym $need\npara sacar $sym $min" },
            levelLabel = { lvl -> "Nível $lvl" },
            noWithdrawUpdate = "Sem atualizações de saque",
            tutorialBanner = "Complete níveis para ganhar recompensas! Quanto mais níveis completar, mais você ganha!",
            pinchToZoomHint = "Afaste os dedos para dar zoom",
            taskCenterTitle = "Central de Tarefas",
            dailyTasksTab = "Tarefas Diárias",
            careerTasksTab = "Tarefas Carreira",
            claimBtn = "Resgatar",
            incompleteBtn = "Incompleto",
            claimedBtn = "Resgatado",
            dailyLoginTask = "Login diário",
            completeLevelsTask = { n -> "Complete $n níveis" },
            watchAdsTask = { n -> "Assistir $n vídeos" },
            taskRewardTitle = "Prêmio da Tarefa",
            levelSuccessTitle = "Sucesso!",
            watchAdToClaimBtn = "Ver vídeo para resgatar tudo",
            claimBaseOnlyBtn = { amt -> "Resgatar apenas $sym $amt" },
            nextLevelBtn = "Próximo Nível (Next Level)",
            watchingVideoToast = "Resgatando grande prêmio...",
            continueHeader = "Continuar?",
            outOfLivesTitle = "Sem Vidas!",
            outOfLivesSubtitle = "Não desista! Reviva grátis e continue jogando!",
            freeReviveBtn = "Reviver Grátis",
            tryAgainBtn = "Tentar Novamente",
            withdrawScreenTitle = "Saque",
            currentBalanceLabel = "Saldo Atual",
            withdrawTierSection = "Níveis de Saque",
            withdrawInstructionsSection = "Instruções de Saque:",
            withdrawRuleText = { tier -> "Pelas regras da plataforma, o valor deste nível é $sym $tier" },
            withdrawNeededText = { tier, need -> "Para sacar $sym $tier, você precisa de mais $sym $need" },
            withdrawActionBtn = { tier -> "Sacar $sym $tier" },
            accountDetailsHeader = "Dados da Conta",
            selectAccountMethodSubtitle = "Selecione o método de pagamento",
            accountInputPlaceholder = "Digite seu número de celular ou e-mail",
            nameInputPlaceholder = "Digite seu nome completo",
            submitBtn = "Enviar",
            confirmWithdrawHeader = "Confirmar Saque",
            accountFieldLabel = "Conta",
            nameFieldLabel = "Nome",
            invalidAccountToast = "Insira uma conta válida",
            insufficientBalanceToast = { need -> "Saldo insuficiente, faltam $sym $need" },
            withdrawSubmittedToast = { tier -> "Pedido de saque de $sym $tier enviado!" },
            settingsTitle = "Configurações e Idioma",
            soundLabel = "Efeitos Sonoros",
            vibrationLabel = "Vibração",
            languageLabel = "Selecionar Idioma (Language)",
            selectLevelLabel = "Selecionar Nível (100+ Níveis)",
            restartLevelLabel = "Reiniciar Nível",
            closeBtn = "Fechar",
            broadcastMessages = listOf(
                "Parabéns Lucas***! Sacou $sym 384.00 com sucesso!",
                "Parabéns Julia***! Sacou $sym 240.00 com sucesso!",
                "Parabéns Pedro***! Sacou $sym 480.00 com sucesso!"
            )
        )

        AppLanguage.ENGLISH -> LocalizedStrings(
            withdrawBtn = "withdraw",
            moreToWithdrawTop = { need, min -> "$sym $need more\nto withdraw $sym $min" },
            levelLabel = { lvl -> "Level $lvl" },
            noWithdrawUpdate = "No withdrawal updates",
            tutorialBanner = "Complete levels to earn cash rewards! The more levels you clear, the more opportunities to earn!",
            pinchToZoomHint = "Spread fingers outward to zoom",
            taskCenterTitle = "Task Center",
            dailyTasksTab = "Daily Tasks",
            careerTasksTab = "Career Tasks",
            claimBtn = "Claim",
            incompleteBtn = "Incomplete",
            claimedBtn = "Claimed",
            dailyLoginTask = "Daily Login",
            completeLevelsTask = { n -> "Complete $n Level${if (n > 1) "s" else ""}" },
            watchAdsTask = { n -> "Watch $n Video${if (n > 1) "s" else ""}" },
            taskRewardTitle = "Task Reward",
            levelSuccessTitle = "Success",
            watchAdToClaimBtn = "Watch Video to Claim",
            claimBaseOnlyBtn = { amt -> "Claim only $sym $amt" },
            nextLevelBtn = "Next Level",
            watchingVideoToast = "Watch video to claim big reward",
            continueHeader = "Continue?",
            outOfLivesTitle = "Out of Lives!",
            outOfLivesSubtitle = "Don't give up! Revive for free and keep fighting!",
            freeReviveBtn = "Free Revive",
            tryAgainBtn = "Try Again",
            withdrawScreenTitle = "Withdraw",
            currentBalanceLabel = "Current Balance",
            withdrawTierSection = "Withdraw Tier",
            withdrawInstructionsSection = "Withdraw Instructions:",
            withdrawRuleText = { tier -> "According to platform rules, this tier payment amount is $sym $tier" },
            withdrawNeededText = { tier, need -> "To withdraw $sym $tier, you need $sym $need more" },
            withdrawActionBtn = { tier -> "Withdraw $sym $tier" },
            accountDetailsHeader = "Enter Account Details",
            selectAccountMethodSubtitle = "Select account method",
            accountInputPlaceholder = "Please enter your account (mobile number or email)",
            nameInputPlaceholder = "Please enter your name",
            submitBtn = "Submit",
            confirmWithdrawHeader = "Confirm Withdraw Details",
            accountFieldLabel = "Account",
            nameFieldLabel = "Name",
            invalidAccountToast = "Please enter a valid account",
            insufficientBalanceToast = { need -> "Insufficient balance, $sym $need short" },
            withdrawSubmittedToast = { tier -> "Withdrawal request for $sym $tier submitted!" },
            settingsTitle = "Settings & Language",
            soundLabel = "Sound Effects",
            vibrationLabel = "Vibration",
            languageLabel = "Select Language (8 Languages)",
            selectLevelLabel = "Select Level (100+ Levels)",
            restartLevelLabel = "Restart Current Level",
            closeBtn = "Close",
            broadcastMessages = listOf(
                "Congrats Araf***! Successfully withdrew $sym 84.00!",
                "Congrats Fatema***! Successfully withdrew $sym 42.00!",
                "Congrats Kama***! Successfully withdrew $sym 168.00!",
                "Congrats Tanv***! Successfully withdrew $sym 252.00!"
            )
        )
    }
}
